# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhimosisStretcher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhimosisStretcher
  pod 'DZNEmptyDataSet'
  pod 'Google-Mobile-Ads-SDK'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/Buttons+Theming'
  pod 'MaterialComponents/TextFields'

  target 'PhimosisStretcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
